export interface Product {
  id: string
  name: string
  nameAr: string
  description?: string
  descriptionAr?: string
  price: number
  original_price?: number
  image: string
  category: string
  categoryAr: string
  brand: string
  isOnSale?: boolean
  subcategory?: string
  subcategoryAr?: string
  discountPercent?: number
}

export const products: Product[] = [
  // ========== العناية بالبشرة - Skin Care ==========
  {
    id: "1",
    name: "JUMISO Niacinamide 20 Serum 40ml",
    nameAr: "سيروم جوميسو نياسيناميد 20 - 40مل",
    price: 77860,
    image: "/jumiso-niacinamide-20-serum-bottle-korean-skincare.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "JUMISO",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "2",
    name: "Anua Azelaic Acid 3 CICA Skin Clarifying Toner 250ml",
    nameAr: "تونر أنوا أزيلايك أسيد 3 سيكا - 250مل",
    price: 77860,
    image: "/anua-green-toner-bottle-azelaic-acid-korean-skinca.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ANUA",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "3",
    name: "SKIN 1004 Madagascar Centella Tone Brightening Dark Spot Ampoule Pad 60 Pads",
    nameAr: "باد سكين1004 سنتيلا لتفتيح البقع الداكنة 60 قطعة",
    price: 77860,
    image: "/skin1004-green-container-jar-toner-pads-centella-k.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Skin1004",
    subcategory: "masks",
    subcategoryAr: "ماسكات وباد",
    discountPercent: 0,
  },
  {
    id: "4",
    name: "ANUA Serum Mini Trio Set",
    nameAr: "مجموعة أنوا سيروم ميني تريو",
    price: 96180,
    image: "/three-mini-serum-bottles-set-anua-korean-skincare-.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ANUA",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "5",
    name: "Madeca Cream Time Reverse 50ml",
    nameAr: "كريم ماديكا تايم ريفيرس 50مل",
    price: 75112,
    image: "/centellian24-madeca-cream-jar-gold-elegant-anti-ag.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "CENTELLIAN24",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "6",
    name: "La Roche-Posay Tolériane Dermallergo Fluid 40ml",
    nameAr: "لاروش بوزيه تولريان ديرماليرجو فلويد 40مل",
    price: 114500,
    image: "/la-roche-posay-toleriane-white-tube-french-pharmac.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "La Roche-Posay",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "7",
    name: "Avène Cicalfate+ Repairing Protective Cream",
    nameAr: "كريم أفين سيكالفات+ المرمم والواقي",
    price: 56792,
    image: "/avene-cicalfate-white-tube-orange-cap-french-pharm.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Avène",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "8",
    name: "Centella Air-Fit Suncream Plus SPF50+ PA++++",
    nameAr: "واقي شمس سنتيلا إير فيت بلس SPF50+",
    price: 65952,
    image: "/skin1004-green-sunscreen-tube-spf50-centella-korea.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Skin1004",
    subcategory: "sunscreen",
    subcategoryAr: "واقي شمس",
    discountPercent: 0,
  },
  {
    id: "9",
    name: "Madagascar Centella Air-Fit Suncream Light SPF30 PA++++",
    nameAr: "واقي شمس سنتيلا إير فيت لايت SPF30",
    price: 72364,
    originalPrice: 81524,
    isOnSale: true,
    image: "/skin1004-light-green-sunscreen-tube-spf30-centella.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Skin1004",
    subcategory: "sunscreen",
    subcategoryAr: "واقي شمس",
    discountPercent: 11.4,
  },
  {
    id: "10",
    name: "VT Reedle Shot Lip Plumper Beginner 4.3g",
    nameAr: "مكبر شفاه في تي ريدل شوت للمبتدئين 4.3جم",
    price: 54044,
    image: "/vt-cosmetics-lip-plumper-gloss-tube-korean-beauty.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "VT COSMETICS",
    subcategory: "lipbalm",
    subcategoryAr: "مرطب شفاه",
    discountPercent: 0,
  },
  {
    id: "11",
    name: "Abib PDRN Retinal Eye Patch Glow Jelly 60 Patches",
    nameAr: "باتشات أبيب PDRN ريتينال للعين 60 قطعة",
    price: 77860,
    image: "/abib-eye-patches-jar-gold-elegant-korean-skincare.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Abib",
    subcategory: "eyecare",
    subcategoryAr: "كريمات العين",
    discountPercent: 0,
  },
  {
    id: "12",
    name: "SKIN1004 Madagascar Centella Tone Brightening Capsule Ampoule 50ml",
    nameAr: "أمبول سكين1004 سنتيلا لتفتيح البشرة 50مل",
    price: 50380,
    image: "/skin1004-brightening-ampoule-serum-bottle-dropper-.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Skin1004",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "13",
    name: "Dr.Althea 345 Relief Cream 50ml",
    nameAr: "كريم دكتور ألثيا 345 ريليف 50مل",
    price: 89768,
    image: "/dr-althea-345-relief-cream-white-tube-korean-skinc.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Dr. Althea",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "14",
    name: "Medicube Zero Pore Pads 2.0",
    nameAr: "باد ميديكيوب زيرو بور 2.0",
    price: 99844,
    image: "/medicube-pore-pads-container-red-white-korean-skin.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Medicube",
    subcategory: "masks",
    subcategoryAr: "ماسكات وباد",
    discountPercent: 0,
  },
  {
    id: "15",
    name: "EQQUALBERRY Vitamin Illuminating Serum 30ml",
    nameAr: "سيروم إيكوالبيري فيتامين للإشراق 30مل",
    price: 87020,
    image: "/eqqualberry-vitamin-c-serum-bottle-orange-dropper-.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "EQQUALBERRY",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "16",
    name: "PURITO SEOUL Mighty Bamboo Panthenol Cream 100ml",
    nameAr: "كريم بوريتو سيول بامبو بانثينول 100مل",
    price: 73280,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Purito SEOUL",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "17",
    name: "Skin1004 Centella Travel Kit",
    nameAr: "مجموعة سفر سكين1004 سنتيلا",
    price: 100760,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Skin1004",
    subcategory: "other",
    subcategoryAr: "أخرى",
    discountPercent: 0,
  },
  {
    id: "18",
    name: "Madagascar Centella Light Cleansing Oil 200ml",
    nameAr: "زيت تنظيف سنتيلا الخفيف 200مل",
    price: 65952,
    originalPrice: 81524,
    isOnSale: true,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Skin1004",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 19.1,
  },
  {
    id: "19",
    name: "KSECRET SEOUL 1988 Eye Cream Retinal Liposome 4% 30ml",
    nameAr: "كريم عيون كي سيكريت سيول 1988 ريتينال 30مل",
    price: 68700,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "KSECRET",
    subcategory: "eyecare",
    subcategoryAr: "كريمات العين",
    discountPercent: 0,
  },
  {
    id: "20",
    name: "ANUA 10% Niacinamide+ 4% Tranexamic Acid Serum 30ml",
    nameAr: "سيروم أنوا نياسيناميد 10% + ترانيكساميك 4% - 30مل",
    price: 90684,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ANUA",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "21",
    name: "Medicube TXA+Niacinamide 15% Glow Facial Serum 30ml",
    nameAr: "سيروم ميديكيوب للإشراق 30مل",
    price: 65952,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Medicube",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "22",
    name: "SKIN1004 Madagascar Centella Poremizing Quick Clay Stick Mask 27g",
    nameAr: "ماسك سكين1004 بالطين للمسام 27جم",
    price: 59540,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Skin1004",
    subcategory: "masks",
    subcategoryAr: "ماسكات وباد",
    discountPercent: 0,
  },
  {
    id: "23",
    name: "SKIN1004 Madagascar Centella Poremizing Fresh Ampoule 100ml",
    nameAr: "أمبول سكين1004 للمسام 100مل",
    price: 68700,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Skin1004",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "24",
    name: "ANUA Azelaic Acid 10 Hyaluronic Redness Soothing Pad 90 Pads",
    nameAr: "باد أنوا أزيلايك أسيد 10 هيالورونيك 90 قطعة",
    price: 96180,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ANUA",
    subcategory: "masks",
    subcategoryAr: "ماسكات وباد",
    discountPercent: 0,
  },
  {
    id: "25",
    name: "ANUA Niacinamide 5 TXA Brightening Pad 60 Pads",
    nameAr: "باد أنوا نياسيناميد 5 للتفتيح 60 قطعة",
    price: 96180,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ANUA",
    subcategory: "masks",
    subcategoryAr: "ماسكات وباد",
    discountPercent: 0,
  },
  {
    id: "26",
    name: "Ceramide Ato Concentrate Cream 230ml",
    nameAr: "كريم إليون سيراميد أتو المركز 230مل",
    price: 96180,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ILLIYOON",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "27",
    name: "LION Pair Acne Cream W 14g",
    nameAr: "كريم لايون بير لحب الشباب 14جم",
    price: 29312,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "LION",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "28",
    name: "Anua Azelaic Acid 10 Hyaluron Redness Soothing Serum 30ml",
    nameAr: "سيروم أنوا أزيلايك أسيد 10 هيالورون 30مل",
    price: 96180,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ANUA",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "29",
    name: "Dr.Althea Gentle Vitamin C Serum 30ml",
    nameAr: "سيروم دكتور ألثيا فيتامين سي اللطيف 30مل",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Dr. Althea",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "30",
    name: "SKIN1004 Probio-Cica Enrich Cream 50ml",
    nameAr: "كريم سكين1004 بروبيو سيكا الغني 50مل",
    price: 81524,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Skin1004",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "31",
    name: "Beauty of Joseon Glow Deep Serum Rice+Alpha-Arbutin",
    nameAr: "سيروم بيوتي أوف جوسون للإشراق العميق",
    price: 73280,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Beauty of Joseon",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "32",
    name: "Dr.Althea Vitamin C Boosting Serum 30ml",
    nameAr: "سيروم دكتور ألثيا فيتامين سي بوستينج 30مل",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Dr. Althea",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "33",
    name: "Isntree Hyaluronic Acid Fresh Sun Serum 50ml",
    nameAr: "سيروم واقي شمس إزنتري هيالورونيك 50مل",
    price: 68700,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Isntree",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "34",
    name: "EQQUALBERRY Bakuchiol Plumping Serum 30ml",
    nameAr: "سيروم إيكوالبيري باكوشيول للنفخ 30مل",
    price: 100760,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "EQQUALBERRY",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "35",
    name: "Medicube PDRN Pink Peptide Serum 30ml",
    nameAr: "سيروم ميديكيوب PDRN بينك ببتيد 30مل",
    price: 73280,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Medicube",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "36",
    name: "Seapuri Scalpy Hair Serum 20ml",
    nameAr: "سيروم سيبوري للشعر وفروة الرأس 20مل",
    price: 87020,
    image: "/marvis-whitening-mint-toothpaste-tube-elegant-ital.jpg",
    category: "hair",
    categoryAr: "العناية بالشعر",
    brand: "Seapuri",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "37",
    name: "Tsubaki Premium EX Repair Hair Mask 180g",
    nameAr: "ماسك تسوباكي بريميوم لإصلاح الشعر 180جم",
    price: 77860,
    image: "/vt-cosmetics-reedle-shot-lip-plumper-gloss-tube-ko.jpg",
    category: "hair",
    categoryAr: "العناية بالشعر",
    brand: "Shiseido",
    subcategory: "masks",
    subcategoryAr: "ماسكات",
    discountPercent: 0,
  },
  {
    id: "38",
    name: "Shiseido Fino Premium Touch Hair Mask 230g",
    nameAr: "ماسك شيسيدو فينو بريميوم للشعر 230جم",
    price: 81524,
    image: "/numbuzin-no3-porcelain-base-tone-up-beige-spf50-ko.jpg",
    category: "hair",
    categoryAr: "العناية بالشعر",
    brand: "Shiseido",
    subcategory: "masks",
    subcategoryAr: "ماسكات",
    discountPercent: 0,
  },
  {
    id: "39",
    name: "A'PIEU Raspberry Hair Vinegar 200ml",
    nameAr: "خل التوت للشعر من أبيو 200مل",
    price: 41220,
    image: "/heimish-all-clean-balm-jar-yellow-korean-cleansing.jpg",
    category: "hair",
    categoryAr: "العناية بالشعر",
    brand: "A'PIEU",
    subcategory: "other",
    subcategoryAr: "أخرى",
    discountPercent: 0,
  },
  {
    id: "40",
    name: "Tree Hut Shea Sugar Body Scrub Coconut Lime 510g",
    nameAr: "مقشر تري هت شيا بالسكر جوز الهند والليمون 510جم",
    price: 72364,
    image: "/haruharu-wonder-black-rice-hyaluronic-toner-bottle.jpg",
    category: "body",
    categoryAr: "العناية بالجسم",
    brand: "Tree Hut",
    subcategory: "scrubs",
    subcategoryAr: "مقشرات",
    discountPercent: 0,
  },
  {
    id: "41",
    name: "Eos Fresh & Cozy Body Lotion 473ml",
    nameAr: "لوشن إيوس فريش آند كوزي للجسم 473مل",
    price: 72364,
    image: "/mary-and-may-cica-teatree-soothing-wash-off-pack-t.jpg",
    category: "body",
    categoryAr: "العناية بالجسم",
    brand: "EOS",
    subcategory: "lotions",
    subcategoryAr: "لوشن ومرطبات",
    discountPercent: 0,
  },
  {
    id: "42",
    name: "Eos Crème de Pistachio Body Lotion 473ml",
    nameAr: "لوشن إيوس كريم الفستق للجسم 473مل",
    price: 72364,
    image: "/celimax-the-real-noni-energy-ampoule-mask-sheet-ko.jpg",
    category: "body",
    categoryAr: "العناية بالجسم",
    brand: "EOS",
    subcategory: "lotions",
    subcategoryAr: "لوشن ومرطبات",
    discountPercent: 0,
  },
  {
    id: "43",
    name: "Uriage Gentle Deodorant Aluminium free 50ml",
    nameAr: "مزيل عرق يورياج جنتل خالي من الألمنيوم 50مل",
    price: 61372,
    image: "/dr-g-red-blemish-clear-soothing-cream-jar-korean-s.jpg",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "Uriage",
    subcategory: "deodorant",
    subcategoryAr: "مزيل عرق",
    discountPercent: 0,
  },
  {
    id: "44",
    name: "Uriage Power 3 Deodorant 50ml",
    nameAr: "مزيل عرق يورياج باور 3 - 50مل",
    price: 61372,
    image: "/etude-house-soonjung-ph-6-5-whip-cleanser-tube-whi.jpg",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "Uriage",
    subcategory: "deodorant",
    subcategoryAr: "مزيل عرق",
    discountPercent: 0,
  },
  {
    id: "45",
    name: "Dove Stick Original 40g",
    nameAr: "ستيك دوف أوريجينال 40جم",
    price: 12824,
    image: "/laneige-cream-skin-refiner-bottle-white-elegant-ko.jpg",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "DOVE",
    subcategory: "other",
    subcategoryAr: "أخرى",
    discountPercent: 0,
  },
  {
    id: "46",
    name: "NIVEA Labello Moisture Lip Balm Soft Rose 4.8g",
    nameAr: "مرطب شفاه لابيلو سوفت روز 4.8جم",
    price: 10076,
    image: "/dr-g-red-blemish-clear-soothing-cream-jar-korean-s.jpg",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "NIVEA",
    subcategory: "lipbalm",
    subcategoryAr: "مرطب شفاه",
    discountPercent: 0,
  },
  {
    id: "47",
    name: "NIVEA Labello Moisture Lip Balm Original 4.8g",
    nameAr: "مرطب شفاه لابيلو أوريجينال 4.8جم",
    price: 10076,
    image: "/dr-g-red-blemish-clear-soothing-cream-jar-korean-s.jpg",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "NIVEA",
    subcategory: "lipbalm",
    subcategoryAr: "مرطب شفاه",
    discountPercent: 0,
  },
  {
    id: "48",
    name: "Dove Original Clean Roll On Deodorant 50g",
    nameAr: "رول أون دوف أوريجينال كلين 50جم",
    price: 12824,
    image: "/dr-g-red-blemish-clear-soothing-cream-jar-korean-s.jpg",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "DOVE",
    subcategory: "deodorant",
    subcategoryAr: "مزيل عرق",
    discountPercent: 0,
  },
  {
    id: "49",
    name: "Mini Colgate Max Fresh Toothpaste 28g + Toothbrush",
    nameAr: "معجون كولجيت ماكس فريش ميني 28جم + فرشاة",
    price: 10076,
    image: "/dr-g-red-blemish-clear-soothing-cream-jar-korean-s.jpg",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "Colgate",
    subcategory: "dental",
    subcategoryAr: "العناية بالأسنان",
    discountPercent: 0,
  },
  {
    id: "50",
    name: "Mini Dove Advanced Care Antiperspirant Deodorant Stick 14g",
    nameAr: "ستيك دوف أدفانسد كير ميني 14جم",
    price: 8244,
    image: "/dr-g-red-blemish-clear-soothing-cream-jar-korean-s.jpg",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "DOVE",
    subcategory: "deodorant",
    subcategoryAr: "مزيل عرق",
    discountPercent: 0,
  },
  {
    id: "51",
    name: "Marvis Whitening Mint Toothpaste 85ml",
    nameAr: "معجون مارفيس وايتنينج مينت 85مل",
    price: 56792,
    image: "/dr-g-red-blemish-clear-soothing-cream-jar-korean-s.jpg",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "Marvis",
    subcategory: "dental",
    subcategoryAr: "العناية بالأسنان",
    discountPercent: 0,
  },
  {
    id: "52",
    name: "VT Reedle Shot Lip Plumper Expert 4.3g",
    nameAr: "مكبر شفاه في تي ريدل شوت للخبراء 4.3جم",
    price: 54044,
    image: "/vt-cosmetics-reedle-shot-lip-plumper-gloss-tube-ko.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "VT COSMETICS",
    subcategory: "lipbalm",
    subcategoryAr: "مرطب شفاه",
    discountPercent: 0,
  },
  {
    id: "53",
    name: "Numbuzin No.3 Porcelain Base-skip Tone Up Beige SPF50+",
    nameAr: "نمبوزين رقم 3 تون أب بيج SPF50+",
    price: 87020,
    image: "/numbuzin-no3-porcelain-base-tone-up-beige-spf50-ko.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Numbuzin",
    subcategory: "sunscreen",
    subcategoryAr: "واقي شمس",
    discountPercent: 0,
  },
  {
    id: "54",
    name: "Cosrx Advanced Snail 96 Mucin Power Essence 100ml",
    nameAr: "كوسركس أدفانسد سنيل 96 إيسينس 100مل",
    price: 81524,
    image: "/cosrx-advanced-snail-96-mucin-power-essence-bottle.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Cosrx",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "55",
    name: "Round Lab Birch Juice Moisturizing Sunscreen SPF50+",
    nameAr: "راوند لاب واقي شمس بيرش جوس SPF50+",
    price: 68700,
    image: "/round-lab-birch-juice-moisturizing-sunscreen-spf50.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Round Lab",
    subcategory: "sunscreen",
    subcategoryAr: "واقي شمس",
    discountPercent: 0,
  },
  {
    id: "56",
    name: "TOCOBO Cotton Soft Sun Stick SPF50+",
    nameAr: "توكوبو واقي شمس ستيك قطني SPF50+",
    price: 59540,
    image: "/tocobo-cotton-soft-sun-stick-spf50-korean-sunscree.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "TOCOBO",
    subcategory: "sunscreen",
    subcategoryAr: "واقي شمس",
    discountPercent: 0,
  },
  {
    id: "57",
    name: "Heimish All Clean Balm 120ml",
    nameAr: "بلسم هيميش أول كلين 120مل",
    price: 65952,
    image: "/heimish-all-clean-balm-jar-yellow-korean-cleansing.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Heimish",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "58",
    name: "B.Lab Matcha Hydrating Foam Cleanser 120ml",
    nameAr: "غسول بي لاب ماتشا المرطب 120مل",
    price: 54044,
    image: "/b-lab-matcha-hydrating-foam-cleanser-green-tube-ko.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "B.Lab",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "59",
    name: "Haruharu WONDER Black Rice Hyaluronic Toner 150ml",
    nameAr: "تونر هاروهارو ووندر بالأرز الأسود 150مل",
    price: 77860,
    image: "/haruharu-wonder-black-rice-hyaluronic-toner-bottle.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Haruharu WONDER",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "60",
    name: "Torriden DIVE-IN Low Molecule Hyaluronic Acid Serum",
    nameAr: "سيروم توريدين DIVE-IN هيالورونيك أسيد",
    price: 81524,
    image: "/torriden-dive-in-low-molecule-hyaluronic-acid-seru.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Torriden",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "61",
    name: "Mary&May CICA Teatree Soothing Wash Off Pack",
    nameAr: "ماسك ماري آند ماي سيكا تي تري المهدئ",
    price: 59540,
    image: "/mary-and-may-cica-teatree-soothing-wash-off-pack-t.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Mary&May",
    subcategory: "masks",
    subcategoryAr: "ماسكات وباد",
    discountPercent: 0,
  },
  {
    id: "62",
    name: "Celimax The Real Noni Energy Ampoule Mask",
    nameAr: "ماسك سيليماكس نوني إنرجي أمبول",
    price: 68700,
    image: "/celimax-the-real-noni-energy-ampoule-mask-sheet-ko.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Celimax",
    subcategory: "masks",
    subcategoryAr: "ماسكات وباد",
    discountPercent: 0,
  },
  {
    id: "63",
    name: "Dr.G R.E.D Blemish Clear Soothing Cream",
    nameAr: "كريم دكتور جي RED المهدئ لحب الشباب",
    price: 96180,
    image: "/dr-g-red-blemish-clear-soothing-cream-jar-korean-s.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Dr.G",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "64",
    name: "Etude House SoonJung pH 6.5 Whip Cleanser",
    nameAr: "غسول إيتود هاوس سون جونج pH 6.5",
    price: 50380,
    image: "/etude-house-soonjung-ph-6-5-whip-cleanser-tube-whi.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Etude House",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "65",
    name: "Laneige Cream Skin Refiner 150ml",
    nameAr: "لانيج كريم سكين ريفاينر 150مل",
    price: 114500,
    image: "/laneige-cream-skin-refiner-bottle-white-elegant-ko.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Laneige",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "66",
    name: "ongredients Calming Cica Gel Cream",
    nameAr: "كريم جل أونجريدينتس سيكا المهدئ",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ongredients",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "67",
    name: "Arencia Rice Enzyme Powder Cleanser",
    nameAr: "غسول أرينسيا إنزيم الأرز البودرة",
    price: 81524,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Arencia",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "68",
    name: "KAO Biore UV Aqua Rich Watery Essence SPF50+",
    nameAr: "واقي شمس كاو بيوري UV أكوا ريتش SPF50+",
    price: 45556,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "KAO",
    subcategory: "sunscreen",
    subcategoryAr: "واقي شمس",
    discountPercent: 0,
  },
  {
    id: "69",
    name: "FULLY Heartleaf Calming Essence 80ml",
    nameAr: "إيسينس فولي هارتليف المهدئ 80مل",
    price: 68700,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "FULLY",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "70",
    name: "Shiseido Senka Perfect Whip Cleanser 120g",
    nameAr: "غسول شيسيدو سينكا بيرفكت ويب 120جم",
    price: 38388,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Shiseido",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "71",
    name: "ANUA Heartleaf 77% Soothing Toner 250ml",
    nameAr: "تونر أنوا هارتليف 77% المهدئ 250مل",
    price: 77860,
    image: "/anua-heartleaf-77-soothing-toner-green-bottle-kore.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ANUA",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "72",
    name: "COSRX Low pH Good Morning Gel Cleanser 150ml",
    nameAr: "غسول كوسركس جود مورنينج جل 150مل",
    price: 54044,
    image: "/cosrx-low-ph-good-morning-gel-cleanser-tube-korean.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Cosrx",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "73",
    name: "Round Lab 1025 Dokdo Toner 200ml",
    nameAr: "تونر راوند لاب دوكدو 200مل",
    price: 72364,
    image: "/round-lab-1025-dokdo-toner-blue-bottle-korean-skin.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Round Lab",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "74",
    name: "Beauty of Joseon Dynasty Cream 50ml",
    nameAr: "كريم بيوتي أوف جوسون داينستي 50مل",
    price: 81524,
    image: "/beauty-of-joseon-dynasty-cream-jar-korean-traditio.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Beauty of Joseon",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "75",
    name: "COSRX Centella Blemish Cream 30ml",
    nameAr: "كريم كوسركس سنتيلا للبثور 30مل",
    price: 50380,
    image: "/cosrx-centella-blemish-cream-tube-korean-acne-skin.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Cosrx",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "76",
    name: "Numbuzin No.5 Vitamin Concentrated Serum",
    nameAr: "سيروم نمبوزين رقم 5 فيتامين مركز",
    price: 96180,
    image: "/numbuzin-no5-vitamin-concentrated-serum-yellow-bot.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Numbuzin",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "77",
    name: "TOCOBO Collagen Brightening Eye Gel Cream",
    nameAr: "كريم جل توكوبو كولاجين للعين",
    price: 59540,
    image: "/tocobo-collagen-brightening-eye-gel-cream-tube-kor.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "TOCOBO",
    subcategory: "eyecare",
    subcategoryAr: "كريمات العين",
    discountPercent: 0,
  },
  {
    id: "78",
    name: "ANUA Heartleaf Pore Control Cleansing Oil",
    nameAr: "زيت أنوا هارتليف للتنظيف ومسام البشرة",
    price: 81524,
    image: "/anua-heartleaf-pore-control-cleansing-oil-green-bo.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ANUA",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "79",
    name: "Medicube Age-R Glutathione Glow Serum",
    nameAr: "سيروم ميديكيوب جلوتاثيون للإشراق",
    price: 87020,
    image: "/medicube-age-r-glutathione-glow-serum-red-bottle-d.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Medicube",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "80",
    name: "Dr.Jart+ Cicapair Cream 50ml",
    nameAr: "كريم دكتور جارت سيكابير 50مل",
    price: 100760,
    image: "/dr-jart-cicapair-cream-green-tube-korean-skincare-.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Dr.Jart+",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "81",
    name: "SOME BY MI AHA BHA PHA 30 Days Miracle Toner",
    nameAr: "تونر سوم باي مي ميراكل 30 يوم",
    price: 65952,
    image: "/some-by-mi-aha-bha-pha-miracle-toner-green-bottle.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "SOME BY MI",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "82",
    name: "Innisfree Green Tea Seed Serum",
    nameAr: "سيروم إنيسفري الشاي الأخضر",
    price: 77860,
    image: "/innisfree-green-tea-seed-serum-green-bottle-droppe.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Innisfree",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "83",
    name: "COSRX The Retinol 0.1 Cream",
    nameAr: "كريم كوسركس ريتينول 0.1",
    price: 81524,
    image: "/cosrx-retinol-0-1-cream-purple-jar-anti-aging.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Cosrx",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "84",
    name: "Laneige Water Sleeping Mask 70ml",
    nameAr: "ماسك لانيج المائي الليلي 70مل",
    price: 114500,
    image: "/laneige-water-sleeping-mask-blue-jar-overnight-hyd.jpg",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Laneige",
    subcategory: "masks",
    subcategoryAr: "ماسكات وباد",
    discountPercent: 0,
  },
  {
    id: "85",
    name: "SKIN1004 Madagascar Centella Ampoule 100ml",
    nameAr: "أمبول سكين1004 سنتيلا 100مل",
    price: 68700,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Skin1004",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "86",
    name: "COSRX Hyaluronic Acid Intensive Cream",
    nameAr: "كريم كوسركس هيالورونيك المركز",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Cosrx",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "87",
    name: "Beauty of Joseon Relief Sun SPF50+",
    nameAr: "واقي شمس بيوتي أوف جوسون ريليف SPF50+",
    price: 65952,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Beauty of Joseon",
    subcategory: "sunscreen",
    subcategoryAr: "واقي شمس",
    discountPercent: 0,
  },
  {
    id: "88",
    name: "Torriden DIVE-IN Cleansing Foam",
    nameAr: "غسول توريدين DIVE-IN الرغوي",
    price: 59540,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Torriden",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "89",
    name: "Round Lab Birch Juice Moisturizing Cream",
    nameAr: "كريم راوند لاب بيرش جوس المرطب",
    price: 77860,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Round Lab",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "90",
    name: "COSRX Full Fit Propolis Synergy Toner",
    nameAr: "تونر كوسركس بروبوليس سينيرجي",
    price: 68700,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Cosrx",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "91",
    name: "Numbuzin No.2 Deep Clean Fresh Cream Cleanser",
    nameAr: "غسول نمبوزين رقم 2 كريمي منظف",
    price: 54044,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Numbuzin",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "92",
    name: "TOCOBO Bio Watery Sun Cream SPF50+",
    nameAr: "واقي شمس توكوبو بايو ووتري SPF50+",
    price: 65952,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "TOCOBO",
    subcategory: "sunscreen",
    subcategoryAr: "واقي شمس",
    discountPercent: 0,
  },
  {
    id: "93",
    name: "Medicube Triple Collagen Serum",
    nameAr: "سيروم ميديكيوب تريبل كولاجين",
    price: 96180,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Medicube",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "94",
    name: "Haruharu WONDER Black Rice Moisture Cream",
    nameAr: "كريم هاروهارو ووندر بالأرز الأسود",
    price: 81524,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Haruharu WONDER",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "95",
    name: "ANUA Heartleaf Pore Deep Cleansing Foam",
    nameAr: "غسول أنوا هارتليف للمسام العميق",
    price: 59540,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ANUA",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "96",
    name: "Mary&May Niacinamide Vitamin C Brightening Mask",
    nameAr: "ماسك ماري آند ماي نياسيناميد وفيتامين سي",
    price: 68700,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Mary&May",
    subcategory: "masks",
    subcategoryAr: "ماسكات وباد",
    discountPercent: 0,
  },
  {
    id: "97",
    name: "Celimax Dual Barrier Skin Wearable Cream",
    nameAr: "كريم سيليماكس ديوال باريير",
    price: 77860,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Celimax",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "98",
    name: "Dr.G Red Blemish Cica Soothing Cream",
    nameAr: "كريم دكتور جي RED سيكا المهدئ",
    price: 87020,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Dr.G",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "99",
    name: "Etude House Soon Jung Sleeping Pack",
    nameAr: "ماسك إيتود هاوس سون جونج الليلي",
    price: 59540,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Etude House",
    subcategory: "masks",
    subcategoryAr: "ماسكات وباد",
    discountPercent: 0,
  },
  {
    id: "100",
    name: "FULLY Heartleaf Calming Cream",
    nameAr: "كريم فولي هارتليف المهدئ",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "FULLY",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "101",
    name: "ongredients Centella Asiatica 100 Ampoule",
    nameAr: "أمبول أونجريدينتس سنتيلا 100",
    price: 65952,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ongredients",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "102",
    name: "Arencia Fresh Powder Cleanser",
    nameAr: "غسول أرينسيا البودرة المنعش",
    price: 68700,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Arencia",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "103",
    name: "KAO Biore UV Aqua Rich Light Up Essence",
    nameAr: "واقي شمس كاو بيوري UV لايت أب",
    price: 50380,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "KAO",
    subcategory: "sunscreen",
    subcategoryAr: "واقي شمس",
    discountPercent: 0,
  },
  {
    id: "104",
    name: "Heimish Marine Care Eye Cream",
    nameAr: "كريم عيون هيميش مارين كير",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Heimish",
    subcategory: "eyecare",
    subcategoryAr: "كريمات العين",
    discountPercent: 0,
  },
  {
    id: "105",
    name: "B.Lab Matcha Hydrating Facial Toner",
    nameAr: "تونر بي لاب ماتشا المرطب",
    price: 59540,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "B.Lab",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "106",
    name: "Shiseido Tsubaki Premium Moist Shampoo 490ml",
    nameAr: "شامبو شيسيدو تسوباكي بريميوم 490مل",
    price: 96180,
    image: "/placeholder.svg?height=400&width=400",
    category: "hair",
    categoryAr: "العناية بالشعر",
    brand: "Shiseido",
    subcategory: "other",
    subcategoryAr: "أخرى",
    discountPercent: 0,
  },
  {
    id: "107",
    name: "Shiseido Fino Hair Treatment 230g",
    nameAr: "علاج شيسيدو فينو للشعر 230جم",
    price: 87020,
    image: "/placeholder.svg?height=400&width=400",
    category: "hair",
    categoryAr: "العناية بالشعر",
    brand: "Shiseido",
    subcategory: "masks",
    subcategoryAr: "ماسكات",
    discountPercent: 0,
  },
  {
    id: "108",
    name: "Tree Hut Moroccan Rose Body Scrub 510g",
    nameAr: "مقشر تري هت الورد المغربي 510جم",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "body",
    categoryAr: "العناية بالجسم",
    brand: "Tree Hut",
    subcategory: "scrubs",
    subcategoryAr: "مقشرات",
    discountPercent: 0,
  },
  {
    id: "109",
    name: "Tree Hut Sugar Scrub Tropical Mango 510g",
    nameAr: "مقشر تري هت المانجو الاستوائي 510جم",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "body",
    categoryAr: "العناية بالجسم",
    brand: "Tree Hut",
    subcategory: "scrubs",
    subcategoryAr: "مقشرات",
    discountPercent: 0,
  },
  {
    id: "110",
    name: "Eos Vanilla Cashmere Body Lotion 473ml",
    nameAr: "لوشن إيوس فانيلا كاشمير للجسم 473مل",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "body",
    categoryAr: "العناية بالجسم",
    brand: "EOS",
    subcategory: "lotions",
    subcategoryAr: "لوشن ومرطبات",
    discountPercent: 0,
  },
  {
    id: "111",
    name: "Dove Deep Moisture Body Wash 500ml",
    nameAr: "غسول دوف ديب مويستشر للجسم 500مل",
    price: 38388,
    image: "/placeholder.svg?height=400&width=400",
    category: "body",
    categoryAr: "العناية بالجسم",
    brand: "DOVE",
    subcategory: "other",
    subcategoryAr: "أخرى",
    discountPercent: 0,
  },
  {
    id: "112",
    name: "NIVEA Soft Light Moisturizer 200ml",
    nameAr: "مرطب نيفيا سوفت لايت 200مل",
    price: 29312,
    image: "/placeholder.svg?height=400&width=400",
    category: "body",
    categoryAr: "العناية بالجسم",
    brand: "NIVEA",
    subcategory: "lotions",
    subcategoryAr: "لوشن ومرطبات",
    discountPercent: 0,
  },
  {
    id: "113",
    name: "Colgate Optic White Toothpaste 75ml",
    nameAr: "معجون كولجيت أوبتيك وايت 75مل",
    price: 20152,
    image: "/placeholder.svg?height=400&width=400",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "Colgate",
    subcategory: "dental",
    subcategoryAr: "العناية بالأسنان",
    discountPercent: 0,
  },
  {
    id: "114",
    name: "Colgate Total Toothpaste 75ml",
    nameAr: "معجون كولجيت توتال 75مل",
    price: 18320,
    image: "/placeholder.svg?height=400&width=400",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "Colgate",
    subcategory: "dental",
    subcategoryAr: "العناية بالأسنان",
    discountPercent: 0,
  },
  {
    id: "115",
    name: "Marvis Classic Strong Mint Toothpaste 85ml",
    nameAr: "معجون مارفيس كلاسيك سترونج مينت 85مل",
    price: 56792,
    image: "/placeholder.svg?height=400&width=400",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "Marvis",
    subcategory: "dental",
    subcategoryAr: "العناية بالأسنان",
    discountPercent: 0,
  },
  {
    id: "116",
    name: "Dove Original Beauty Cream Bar 100g",
    nameAr: "صابون دوف أوريجينال كريمي 100جم",
    price: 12824,
    image: "/placeholder.svg?height=400&width=400",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "DOVE",
    subcategory: "other",
    subcategoryAr: "أخرى",
    discountPercent: 0,
  },
  {
    id: "117",
    name: "NIVEA Lip Balm Cherry Shine 4.8g",
    nameAr: "مرطب شفاه نيفيا كرز شاين 4.8جم",
    price: 10076,
    image: "/placeholder.svg?height=400&width=400",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "NIVEA",
    subcategory: "lipbalm",
    subcategoryAr: "مرطب شفاه",
    discountPercent: 0,
  },
  {
    id: "118",
    name: "Dove Invisible Dry Spray Antiperspirant 150ml",
    nameAr: "بخاخ دوف إنفيزيبل دراي 150مل",
    price: 25648,
    image: "/placeholder.svg?height=400&width=400",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "DOVE",
    subcategory: "deodorant",
    subcategoryAr: "مزيل عرق",
    discountPercent: 0,
  },
  {
    id: "119",
    name: "NIVEA Fresh Natural Deodorant Roll-On 50ml",
    nameAr: "رول أون نيفيا فريش ناتشورال 50مل",
    price: 14656,
    image: "/placeholder.svg?height=400&width=400",
    category: "personal",
    categoryAr: "العناية الشخصية",
    brand: "NIVEA",
    subcategory: "deodorant",
    subcategoryAr: "مزيل عرق",
    discountPercent: 0,
  },
  {
    id: "120",
    name: "EOS Shea Better Body Lotion Berry 473ml",
    nameAr: "لوشن إيوس شيا بيتر بيري 473مل",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "body",
    categoryAr: "العناية بالجسم",
    brand: "EOS",
    subcategory: "lotions",
    subcategoryAr: "لوشن ومرطبات",
    discountPercent: 0,
  },
  {
    id: "121",
    name: "Tree Hut Watermelon Body Scrub 510g",
    nameAr: "مقشر تري هت البطيخ 510جم",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "body",
    categoryAr: "العناية بالجسم",
    brand: "Tree Hut",
    subcategory: "scrubs",
    subcategoryAr: "مقشرات",
    discountPercent: 0,
  },
  {
    id: "122",
    name: "COSRX Acne Pimple Master Patch",
    nameAr: "باتشات كوسركس لحب الشباب",
    price: 27480,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Cosrx",
    subcategory: "other",
    subcategoryAr: "أخرى",
    discountPercent: 0,
  },
  {
    id: "123",
    name: "Laneige Lip Sleeping Mask Berry 20g",
    nameAr: "ماسك لانيج الليلي للشفاه بيري 20جم",
    price: 81524,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Laneige",
    subcategory: "lipbalm",
    subcategoryAr: "مرطب شفاه",
    discountPercent: 0,
  },
  {
    id: "124",
    name: "SOME BY MI Retinol Intense Reactivating Serum",
    nameAr: "سيروم سوم باي مي ريتينول المركز",
    price: 96180,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "SOME BY MI",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "125",
    name: "Innisfree Jeju Cherry Blossom Tone Up Cream",
    nameAr: "كريم إنيسفري تشيري بلوسوم تون أب",
    price: 65952,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Innisfree",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "126",
    name: "Dr.Jart+ Cicapair Tiger Grass Serum",
    nameAr: "سيروم دكتور جارت سيكابير تايجر جراس",
    price: 114500,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Dr.Jart+",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "127",
    name: "SOME BY MI Yuja Niacin Brightening Toner",
    nameAr: "تونر سوم باي مي يوجا نياسين",
    price: 77860,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "SOME BY MI",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "128",
    name: "Innisfree Green Tea Balancing Cream",
    nameAr: "كريم إنيسفري الشاي الأخضر الموازن",
    price: 68700,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Innisfree",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "129",
    name: "COSRX Ultimate Nourishing Rice Overnight Mask",
    nameAr: "ماسك كوسركس الأرز الليلي المغذي",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Cosrx",
    subcategory: "masks",
    subcategoryAr: "ماسكات وباد",
    discountPercent: 0,
  },
  {
    id: "130",
    name: "Laneige Cream Skin Cerapeptide Refiner",
    nameAr: "تونر لانيج كريم سكين سيراببتايد",
    price: 215260,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Laneige",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "131",
    name: "Round Lab Dokdo Cleanser 150ml",
    nameAr: "غسول راوند لاب دوكدو 150مل",
    price: 50380,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Round Lab",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "132",
    name: "Torriden DIVE-IN Low Molecule Hyaluronic Acid Toner",
    nameAr: "تونر توريدين DIVE-IN هيالورونيك",
    price: 72364,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Torriden",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "133",
    name: "Numbuzin No.3 Super Glowing Essence Toner",
    nameAr: "تونر نمبوزين رقم 3 سوبر جلوينج",
    price: 87020,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Numbuzin",
    subcategory: "toners",
    subcategoryAr: "تونرات",
    discountPercent: 0,
  },
  {
    id: "134",
    name: "TOCOBO Vitamin Nourishing Lip Balm",
    nameAr: "مرطب شفاه توكوبو بالفيتامين",
    price: 41220,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "TOCOBO",
    subcategory: "lipbalm",
    subcategoryAr: "مرطب شفاه",
    discountPercent: 0,
  },
  {
    id: "135",
    name: "Medicube Deep Vita C Ampoule",
    nameAr: "أمبول ميديكيوب ديب فيتا سي",
    price: 100760,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Medicube",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "136",
    name: "Haruharu WONDER Black Rice Facial Oil",
    nameAr: "زيت هاروهارو ووندر بالأرز الأسود",
    price: 96180,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Haruharu WONDER",
    subcategory: "serums",
    subcategoryAr: "سيرومات",
    discountPercent: 0,
  },
  {
    id: "137",
    name: "ANUA Heartleaf 70% Intense Calming Cream",
    nameAr: "كريم أنوا هارتليف 70% المهدئ",
    price: 81524,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "ANUA",
    subcategory: "creams",
    subcategoryAr: "كريمات ومرطبات",
    discountPercent: 0,
  },
  {
    id: "138",
    name: "Mary&May White Collagen Cleansing Foam",
    nameAr: "غسول ماري آند ماي كولاجين أبيض",
    price: 54044,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Mary&May",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "139",
    name: "Celimax Noni Light Cleansing Oil",
    nameAr: "زيت سيليماكس نوني للتنظيف",
    price: 65952,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Celimax",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
  {
    id: "140",
    name: "Dr.G pH Cleansing Gel Foam",
    nameAr: "غسول دكتور جي pH جل فوم",
    price: 59540,
    image: "/placeholder.svg?height=400&width=400",
    category: "skincare",
    categoryAr: "العناية بالبشرة",
    brand: "Dr.G",
    subcategory: "cleansers",
    subcategoryAr: "غسولات",
    discountPercent: 0,
  },
]

export const categories = [
  { id: "skincare", nameAr: "العناية بالبشرة", icon: "sparkles" },
  { id: "hair", nameAr: "العناية بالشعر", icon: "wind" },
  { id: "body", nameAr: "العناية بالجسم", icon: "droplets" },
  { id: "personal", nameAr: "العناية الشخصية", icon: "heart" },
]

export const subcategories = {
  skincare: [
    { id: "all", nameAr: "الكل" },
    { id: "serums", nameAr: "سيرومات" },
    { id: "toners", nameAr: "تونرات" },
    { id: "cleansers", nameAr: "غسولات" },
    { id: "creams", nameAr: "كريمات ومرطبات" },
    { id: "masks", nameAr: "ماسكات وباد" },
    { id: "sunscreen", nameAr: "واقي شمس" },
    { id: "eyecare", nameAr: "كريمات العين" },
    { id: "lipbalm", nameAr: "مرطب شفاه" },
  ],
  hair: [
    { id: "all", nameAr: "الكل" },
    { id: "serums", nameAr: "سيرومات" },
    { id: "masks", nameAr: "ماسكات" },
    { id: "other", nameAr: "أخرى" },
  ],
  body: [
    { id: "all", nameAr: "الكل" },
    { id: "scrubs", nameAr: "مقشرات" },
    { id: "lotions", nameAr: "لوشن ومرطبات" },
  ],
  personal: [
    { id: "all", nameAr: "الكل" },
    { id: "deodorant", nameAr: "مزيل عرق" },
    { id: "dental", nameAr: "العناية بالأسنان" },
    { id: "lipbalm", nameAr: "مرطب شفاه" },
    { id: "other", nameAr: "أخرى" },
  ],
}

export const brands = [
  "Abib",
  "ANUA",
  "Arencia",
  "Avène",
  "A'PIEU",
  "B.Lab",
  "Beauty of Joseon",
  "Celimax",
  "CENTELLIAN24",
  "Colgate",
  "Cosrx",
  "DOVE",
  "Dr. Althea",
  "Dr.G",
  "Dr.Jart+",
  "EOS",
  "EQQUALBERRY",
  "Etude House",
  "FULLY",
  "Haruharu WONDER",
  "Heimish",
  "ILLIYOON",
  "Innisfree",
  "Isntree",
  "JUMISO",
  "KAO",
  "KSECRET",
  "La Roche-Posay",
  "Laneige",
  "LION",
  "Marvis",
  "Mary&May",
  "Medicube",
  "NIVEA",
  "Numbuzin",
  "ongredients",
  "Purito SEOUL",
  "Round Lab",
  "Seapuri",
  "Shiseido",
  "SOME BY MI",
  "Skin1004",
  "TOCOBO",
  "Torriden",
  "Tree Hut",
  "Uriage",
  "VT COSMETICS",
]

export interface Coupon {
  id: string
  code: string
  discount: number
  active: boolean
}

export const formatPrice = (price: number, language: "ar" | "en" = "ar") => {
  const formatted = price.toLocaleString("en-US")
  const currency = language === "ar" ? "ج.س" : "SDG"
  return `${formatted} ${currency}`
}

export const initialProducts = products
